_BASE_: "../Base-RCNN-C4.yaml"
MODEL:
  META_ARCHITECTURE: "AdversarialAttackedGeneralizedRCNN"
  BACKBONE:
    NAME: "build_vgg_backbone"
  PROPOSAL_GENERATOR:
    NAME: "PseudoRPN"
  RPN:
    IN_FEATURES: ["vgg4"]
  ROI_HEADS:
    NAME: "PseudoROIHeads"
    NUM_CLASSES: 8
    IN_FEATURES: ["vgg4"]
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
SOLVER:
  STEPS: (40000,)
  MAX_ITER: 40000
  IMG_PER_BATCH_LABEL: 8
  IMG_PER_BATCH_UNLABEL: 8
  BASE_LR: 0.04
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 2000
DATASETS:
  CROSS_DATASET: True
  TRAIN_LABEL: ("cityscapes_train",)
  TRAIN_UNLABEL: ("cityscapes_foggy_train",)
  TEST: ("cityscapes_foggy_val",)
SEMISUPNET:
  Trainer: "aateacher"
  BBOX_THRESHOLD: 0.8
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 20000
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 1.0
  SUP_LOSS_WEIGHT: 1.0
  DIS_TYPE: "vgg4" #["concate","p2","multi"]
  PSEUDO_LABEL_REG: True
  PASTE_MINORITY: True
  ATTACK_SEVERITY: 1.0
TEST:
  EVAL_PERIOD: 500
INPUT:
  FORMAT: "RGB"