_BASE_: "../Base-RCNN-C4.yaml"
MODEL:
  META_ARCHITECTURE: "AdversarialAttackedGeneralizedRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  PROPOSAL_GENERATOR:
    NAME: "PseudoRPN"
  ROI_HEADS:
    NAME: "PseudoROIHeads"
    NUM_CLASSES: 20
SOLVER:
  STEPS: (40000,)
  MAX_ITER: 40000
  IMG_PER_BATCH_LABEL: 8
  IMG_PER_BATCH_UNLABEL: 8
  BASE_LR: 0.01
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 2000
DATASETS:
  CROSS_DATASET: True
  TRAIN_LABEL: ("voc07_trainval","voc12_trainval")
  TRAIN_UNLABEL: ("Clipart1k_train",)
  TEST: ("Clipart1k_test",)
SEMISUPNET:
  Trainer: "aateacher"
  BBOX_THRESHOLD: 0.8
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 20000
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 0.5
  SUP_LOSS_WEIGHT: 1.0
  DIS_TYPE: "res4" #["concate","p2","multi"]
  PSEUDO_LABEL_REG: True
  PASTE_MINORITY: True
  USE_SIGN: True
  ATTACK_SEVERITY: 1.0
TEST:
  EVAL_PERIOD: 500